in: # Во время режима боя
  time: 30 # Время длительности боя
  bossbar: "&fДо окончания режима боя &6{sec}&fсек"
  bossbar-settings: "YELLOW:SOLID"
  action-bar: "&fДо окончания режима боя &6{sec}&fсек"
  title: "&6Вы вошли в режим боя!"
  sub-title: " "
  message: "&fВы &6вошли &fв &6режим боя"
  command: "&cВы не можете использовать команды во время режима боя!"
  use-item: "&cПодождите перед повторным использованием!"
out: # После окончания режима боя
  action-bar: "&6Вы вышли из режима боя!"
  title: "&6Вы вышли из режима боя!"
  sub-title: " "
  message: "&fВы &6вышли &fиз &6режима боя"
cooldowns: # Кулдауны на предметы во время боя
  golden-apple: 5
  ender-pearl: 5
  enchanted-golden-apple: 10
  chorus: 5
