#
# Плейсхолдеры:
# %lastbuyer_time% - возвращает время до обновления скупщика в формате time-format
#

currency:
  coins: "монет"
  tokens: "кристаллов"

single-sell: LEFT # Вид клика, на который можно продавать предмет по 1 штуке
all-sell: RIGHT # Вид клика, на который можно продавать сразу всё количество предмета у игрока

change-samples: queue # Режим смены шаблонов предметов из items.yml, доступны: queue (по порядку), random (по шансам)

samples-queue: # Режим очереди для появления шаблонов предметов из items.yml
  - "1"

update-time: 3600 # Время обновления шаблонов предметов из items.yml в скупщике в секундах

use-headdatabase: false # Использование HeadDataBase

time-format: "{h}ч {m}мин {s}сек" # Для использования внутри плагина, используйте {time}, для внешнего использования с PlaceholderAPI - %glavbuyer_time%

auto-close-gui: true # Использование автоматического закрытия меню скупщика при его обновлении

sounds: # Настройка звуков, для отключения установите значение "-"
  open-gui: BLOCK_LEVER_CLICK # Звук при открытии меню
  sell: ENTITY_PLAYER_LEVELUP # Звук при продаже предмета
  no-item: ENTITY_VILLAGER_NO # Звук при недостаточном количестве предмета
  update: ENTITY_ENDER_DRAGON_AMBIENT # Звук при обновлении скупщика

item-out: # Настройка предмета, который появится на месте товара, у которого закончился лимит количества
  id: "BARRIER" # Айди предмета или головы из HeadDatabase
  name: "&cТовар Отсутствует" # Название предмета
  lore: # Описание предмета
    - " "
    - "&7Товар был ограничен"
    - "&7и убран из наличия"

locale: # Для отключения определенного сообщения - установите ему значение "-"
  prefix: "&6&lLastLord &r&7|" # Префикс перед каждым сообщением
  reload: "&aКонфигурации успешно перезагружены!" # Собщение при перезагрузке конфигураций
  sell: "&aВы успешно продали &ex{amount} {item} &aза &b{money} {currency}&a!" # Сообщение при продаже предмета, где {amount} - кол-во предмета, {item} - название предмета, {money} - общая сумма продажи, {currency} - наименование валюты
  no-item: "&cУ вас недостаточно предмета &e{item} &cдля продажи!" # Сообщение при нехватке предмета для продажи, где {item} - название предмета
  update: "&aСкупщик был обновлён и заполнен новыми предметами!" # Сообщение при обновлении скупищка
  glavbuyer-use: "&cИспользуйте: /lastbuyer <reload|update>" # Сообщение при неправильном использовании команды /lastbuyer