#
# Плейсхолдеры:
# %glavcrypto_<криптовалюта>% - возвращает количество криптовалюты у игрока
# %glavcrypto_<криптовалюта>_price% - возвращает стоимость криптовалюты
#

use-headdatabase: false # Использование HeadDataBase

update-time: 60 # Время обновления цен на криптовалюты в секундах

min-send: 0.1 # Минимальное количество перевода
max-send: 100000 # Максимальное количество перевода
min-buy: 0.0001 # Минимальное количество покупки
max-buy: 100000 # Максимальное количество покупки
min-sell: 0.0001 # Минимальное количество продажи
max-sell: 100000 # Максимальное количество продажи

coins: # Список криптовалют
  - btc
  - eth
  - ton

sounds: # Настройка звуков, для отключения установите значение "-"
  open-gui: BLOCK_LEVER_CLICK # Звук при открытии меню
  send: ENTITY_PLAYER_LEVELUP # Звук при отправке криптовалюты
  buy: ENTITY_PLAYER_LEVELUP # Звук при покупке криптовалюты
  sell: ENTITY_PLAYER_LEVELUP # Звук при продаже криптовалюты
  limit: ENTITY_VILLAGER_NO # Звук при лимите операции
  no-exists-coin: ENTITY_VILLAGER_NO # Звук при недостаточном количестве криптовалюты
  yourself: ENTITY_VILLAGER_NO # Звук при отправке криптовалюты самому себе
  no-money: ENTITY_VILLAGER_NO # Звук при нехватке денег для покупки криптовалюты
  no-coin: ENTITY_VILLAGER_NO # Звук при нехватке криптовалюты для продажи

locale: # Для отключения определенного сообщения - установите ему значение "-"
  prefix: "&6&lLastLord &r&7|" # Префикс перед каждым сообщением
  reload: "&aКонфигурации успешно перезагружены!" # Собщение при перезагрузке конфигураций
  buy: "&aВы успешно купили &e{amount} {crypto} &aза &6{money} монет&a!" # Сообщение при покупке криптовалюты, где {amount} - кол-во криптовалюты, {crypto} - название криптовалюты, {money} - общая сумма продажи
  sell: "&aВы успешно продали &e{amount} {crypto} &aза &6{money} монет&a!" # Сообщение при продаже криптовалюты, где {amount} - кол-во криптовалюты, {crypto} - название криптовалюты, {money} - общая сумма продажи
  send: # Сообщения при отправке криптовалюты от одного игрока другому
    sender: "&aВы успешно отправили &e{amount} {crypto} &aигроку &b{recipient}&a!"
    recipient: "&aВы успешно получили &e{amount} {crypto} &aот игрока &b{sender}&a!"
  limit: "&cЛимит данной операции составляет от {min} до {max}!" # Сообщение при лимите операции
  no-exists-coin: "&cКриптовалюта {crypto} не существует или не доступна!" # Сообщение о не доступной криптовалюте
  yourself: "&cВы не можете отправлять криптовалюту самому себе!" # Сообщение при отправке криптовалюты самому себе
  no-money: "&cУ вас недостаточно денег!" # Сообщение при нехватке денег для покупки криптовалюты
  no-coin: "&cУ вас недостаточно криптовалюты!" # Сообщение при нехватке криптовалюты для продажи